// little tricky since the version.py is generated by the npm build
// and is then handled into dist by the npm, while the package part
// just copies in some files from the python backend

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const version = execSync("git describe --tags --always --dirty", {
  encoding: "utf8",
}).trim();

const output = `# Auto-generated - do not edit
APP_NAME = "ESP32-S3 IMU Monitor - Web GUI STA/AP - LCD Status"
APP_VERSION = "${version}"
`;

const filename = path.join(__dirname, "../public", "version.py");

fs.writeFileSync(filename, output);

console.log(`Generated version.py: ${version}`);
